import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatToolbarModule, MatButtonModule, MatSidenavModule, 
  MatIconModule, MatListModule, MatCardModule, MatFormFieldModule, 
  MatInputModule, MatMenuModule, MatSnackBarModule, MatProgressBarModule, 
  MatTableModule, MatProgressSpinnerModule, MatCheckboxModule, 
  MatPaginatorModule, MatSortModule, MatDialogModule, MatSelectModule, MatGridListModule, 
  MatTooltipModule, MatDatepickerModule, MatSlideToggleModule, MatNativeDateModule, MatStepperModule, 
  MatAutocompleteModule, MatChipsModule, MatRadioModule, MatTabsModule, MatButtonToggleModule } from '@angular/material';

@NgModule({
  imports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatMenuModule,
    MatSnackBarModule,
    MatProgressBarModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatProgressSpinnerModule,
    MatCheckboxModule,
    MatDialogModule,
    MatSelectModule,
    MatGridListModule,
    MatTooltipModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSlideToggleModule,
    MatStepperModule,
    MatAutocompleteModule,
    MatChipsModule,
    MatRadioModule,
    MatTabsModule,
    MatButtonToggleModule,
  ],
  exports: [
    MatToolbarModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatMenuModule,
    MatSnackBarModule,
    MatProgressBarModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatProgressSpinnerModule,
    MatCheckboxModule,
    MatDialogModule,
    MatSelectModule,
    MatGridListModule,
    MatTooltipModule,
    MatDatepickerModule,
    MatSlideToggleModule,
    MatStepperModule,
    MatAutocompleteModule,
    MatChipsModule,
    MatRadioModule,
    MatTabsModule,
    MatButtonToggleModule
  ],
  declarations: []
})
export class MaterialModule { }
